apiVersion: v1
kind: Secret
metadata:
  name: product-svc-secrets
data:
  dbUser: YWRtaW4=
  dbPassword: YTFwaGFPZmZpY2UxXw==
  dbUrl: amRiYzpvcmFjbGU6dGhpbjpAcHJvZHVjdF9MT1c/VE5TX0FETUlOPS9oZWxpZG9uL3dhbGxldA==
