server:
  port: 8080
  host: 0.0.0.0
  ssl:
    private-key:
      keystore-resource-path: "certificate.p12"
      keystore-passphrase: "helidon"
  experimental:
    http2:
      enable: true
      max-content-length: 16384